services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: car-rental

  app:
    build: .
    ports:
      - "7777"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/car-rental
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db